version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-pranjal1712}/apex-energy-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    image: ${DOCKERHUB_USERNAME:-pranjal1712}/apex-energy-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: apex_network
