apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apex-ingress
  namespace: apex-energy
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apex-frontend-svc
            port:
              number: 80
