apiVersion: v1
kind: Secret
metadata:
  name: apex-secrets
  namespace: apex-energy
type: Opaque
data:
  # Values must be Base64 encoded: echo -n "YOUR_VALUE" | base64
  SECRET_KEY: "PEJBU0U2NF9FTkNPREVEX1NFQ1JFVF9LRVk+"
  GROQ_API_KEY: "PEJBU0U2NF9FTkNPREVEX0dST1FfQVBJX0tFWV9MSVNUPg=="
  GROQ_API_KEYS: "PEJBU0U2NF9FTkNPREVEX0dST1FfQVBJX0tFWVNfTElTVD4="
  TAVILY_API_KEY: "PEJBU0U2NF9FTkNPREVEX1RBVklMWV9BUElfS0VZPg=="
  REDIS_URL: "PEJBU0U2NF9FTkNPREVEX1JFRElTX1VSTD4="
  QDRANT_URL: "PEJBU0U2NF9FTkNPREVEX1FEUkFOVF9VSTD4="
  QDRANT_API_KEY: "PEJBU0U2NF9FTkNPREVEX1FEUkFOVF9BUElfS0VZPg=="
  VITE_GOOGLE_CLIENT_ID: "PEJBU0U2NF9FTkNPREVEX1ZJVEVfR09PR0xFX0NMSUVOVF9JRD4="
  # Mail Settings
  MAIL_USERNAME: "PEJBU0U2NF9FTkNPREVEX01BSUxfVVNFUk5BTUU+"
  MAIL_PASSWORD: "PEJBU0U2NF9FTkNPREVEX01BSUxfUEFTU1dPUkQ+"
  MAIL_FROM: "PEJBU0U2NF9FTkNPREVEX01BSUxfRlJPTT4="
  MAIL_FROM_NAME: "PEJBU0U2NF9FTkNPREVEX01BSUxfRlJPTV9OQU1FPg=="
  MAIL_PORT: "NDY1" # Base64 for 465
  MAIL_SERVER: "c210cC5nbWFpbC5jb20=" # Base64 for smtp.gmail.com
