apiVersion: v1
kind: Secret
metadata:
  name: apex-secrets
  namespace: apex-energy
type: Opaque
data:
  # Values must be Base64 encoded: echo -n "YOUR_VALUE" | base64
  SECRET_KEY: "c3VwZXItc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZA=="
  GROQ_API_KEY: "Z3NrX1pLVzd1dTd0RUpYUVVES3VLRVQ0V0dkeWIzRllwUWMwY3RRa0dOTWRBbmRESnVZcnlzWGIsZ3NrX1Fqb1dEcDVtWmFYb2RMa2gxbDlQV0dkeWIzRllMNmhEQXRnd0I2NU5XeU1vQVVoZW5IT08sZ3NrX0FyUUcyV25nZ0swaG1CeG1iSHFJV0dkeWIzRllTTGEwSTRBMk1nU3JpVzZHMVhkbFgyeTk="
  GROQ_API_KEYS: "Z3NrX0FQYUlWTTRKdllvWW5reEJyMkxhV0dkeWIzRlk1c2o5RnQ0QjhPTGNBMmRBQVc0RGcyTzcsZ3NrXzRvdFp0M3U2MXJPRXFRYzVRakN2V0dkeWIzRlk1d3Zad3BkZGtJWFZ2S3JKbGdVT0NXak4sZ3NrX2x0cjJpa1NpbWJDV3V0VFVxNHVaV0dkeWIzRllaMXY5YWlZNGZWN2hweWVobjBPdzkydHUsZ3NrX2lkS1NTUFU2eDFaQkJPTkpFdnBZV0dkeWIzRllsWnNsMW8wd2Z0OEl0VkxUZ0dZbTh1Y00="
  TAVILY_API_KEY: "dHZseS1kZXYtMlVxYUFKLXFWVmdURlA0c2xwbkZlMlBydnhQTmdocGNKamFTeEFuVm1xQklYQlhiOA=="
  REDIS_URL: "cmVkaXM6Ly9kZWZhdWx0OkFoUjNTdlFSbDdyNnoyVE9oZmV1aGFOMVZPck03RVoxQHJlZGlzLTEzNTQxLmMxMC51cy1lYXN0LTEtMy5lYzIuY2xvdWQucmVkaXNsYWJzLmNvbToxMzU0MQ=="
  QDRANT_URL: "aHR0cHM6Ly80NjVlYjgxYi05OGU4LTQ5ZGQtYjU4Ny03NDdjODJmNmQ2NTUudXMtd2VzdC0xLTAuYXdzLmNsb3VkLnFkcmFudC5pbzo2MzMz"
  QDRANT_API_KEY: "ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhZMk5sYzNNaU9pSnRJaXdpYzNWaWFtVmpkQ0k2SW1Gd2FTMXJaWGs2TkdNMk1EVXlPRGt0T0dGa09TMDBaRGRtTFRsaU9HVXROREV4TXpkbU5URmlNekF4SW4wLkRUUURIbEh3enJoSS1pa3F4cG5WZFZmYVByZllNN0JTMUJLU2doREhwT1U="
  VITE_GOOGLE_CLIENT_ID: "MzgzMTQ1MDEyMzA3LXYwZzhocmIyZTJkYzU5a3M2bG4wZjJkMXIzYWdlbzFuLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t"
  # Mail Settings
  MAIL_USERNAME: "c2hhcm1hYTI5MjM0QGdtYWlsLmNvbQ=="
  MAIL_PASSWORD: "YWt1YyB5bnJ5IG5vdGogaXZ2eg=="
  MAIL_FROM: "c2hhcm1hYTI5MjM0QGdtYWlsLmNvbQ=="
  MAIL_FROM_NAME: "QXBleCBFbmVyZ3kgQUk="
  MAIL_PORT: "NDY1" # Base64 for 465
  MAIL_SERVER: "c210cC5nbWFpbC5jb20=" # Base64 for smtp.gmail.com
